sudo: required
services:
  - docker

before_install:
  - docker build -t hootielander/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run myhootielander/react-test npm test -- --coverage

after_sucess:
  - docker build -t hootielander/multi-client ./client
  - docker build -t hootielander/multi-nginx ./nginx
  - docker build -t hootielander/multi-server ./server
  - docker build -t hootielander/multi-worker ./worker
